### ISSUE TITLE
Подключение по WiFi

### ISSUE THREAD

**Issue by Andrejka1965** [NovoselovMilk/Brushed-ESC-with-display#1]
Невозможно подключиться к точке доступа. Нет описания, пароля, параметров настройки ESC,  прошу помочь.

**Comment by NovoselovMilk** [comment]
Спасибо, обновил. Посмотрите полное видео про этот регулятор - https://youtu.be/tsTFnizV5i4?si=mrGLiQ-2rJ-aG7hx

**Comment by Andrejka1965** [comment]
Добрый. Сегодня протестирую на Node MCU, Wemos mini, результаты сообщу.
Благодарю.
